spring:
  h2:
    console:
      enabled: true
  datasource:
    url: "jdbc:h2:mem:testdb;MODE=MYSQL;DB_CLOSE_DELAY=-1"
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        format_sql: true
    hibernate:
      ddl-auto: create-drop
    open-in-view: false
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          timeout: 5000
          starttls:
            enable: true
server:
  servlet:
    encoding:
      force: true
      charset: UTF-8
  port: 26134

shelter:
  name: abandoned animals api
  description: You can refer to abandoned animal data.
  api:
    url: http://openapi.animal.go.kr/openapi/service/rest/abandonmentPublicSrvc
    key: ${SHELTER_API_KEY}

cloud:
  aws:
    s3:
      bucket: compet-dev-image
    region:
      auto: false
      static: ap-northeast-2
    stack:
      auto: false
    credentials:
      instance-profile: true

logging:
  level:
    com:
      amazonaws:
        util:
          EC2MetadataUtils: error

jwt:
  header: authorization
  issuer: compet
  client-secret: N4VZuLd3A47Y6lhISWAl4XTS6nB4GFncraNDdAUq+uA=
  expiry-seconds: 6000
