spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: create-drop
    open-in-view: false
server:
  servlet:
    encoding:
      force: true
      charset: UTF-8
