spring:
  datasource:
    url: jdbc:mysql://${DEV_DB_HOSTNAME}:${DEV_DB_PORT}/${PROD_DB_DATABASE}?zeroDateTimeBehavior=convertToNull
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none
    open-in-view: false
