spring:
  datasource:
    url: jdbc:mysql://${DEV_DB_HOSTNAME}:${DEV_DB_PORT}/${DEV_DB_DATABASE}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
